# Generated by Django 3.0.8 on 2021-03-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='name_country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='name_state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
