# Generated by Django 3.0.8 on 2021-03-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20210316_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='name_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='name_state',
            new_name='state',
        ),
    ]
