# Generated by Django 3.0.8 on 2021-03-16 09:59

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_auto_20210316_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='courses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CHEM', 'CHEM')], max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='no_of_students',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CHEM', 'CHEM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='year_founded',
            field=models.IntegerField(null=True),
        ),
    ]
