# Generated by Django 3.0.8 on 2021-03-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_auto_20210316_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='courses',
        ),
    ]
