# Generated by Django 3.0.8 on 2021-03-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_remove_college_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='city',
        ),
    ]
