# Generated by Django 3.0.8 on 2021-03-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_remove_college_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
